version: '3.9'
services:
    es01:
        container_name: es01
        image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
        environment:
            - discovery.type=single-node
            - path.repo=/usr/share/elasticsearch/backups
        restart: always
        ports:
            - 9200:9200
        networks:
            - elastic
        volumes:
            - es_data:/usr/share/elasticsearch/data
            - ./backups:/usr/share/elasticsearch/backups

    kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:8.8.2
        restart: always
        ports:
            - 5601:5601
        networks:
            - elastic

volumes:
    es_data:
networks:
    elastic: